### ISSUE TITLE
v5.0 $.fn.almFilter is not a function

### ISSUE THREAD

**Issue by grayfoxsthlm** [dcooney/wordpress-ajax-load-more#158]
I have updated plugin to v5.0.1 and now my filters on the frontend showing console error $.fn.almFilter is not a function.

Same code is working well with 4.2.0.1

**Comment by dcooney** [comment]
@grayfoxsthlm https://connekthq.com/ajax-load-more-5-0/

**Comment by grayfoxsthlm** [comment]
Enabling Legacy support solved the issue. Thanks!

**Comment by magarishor** [comment]
Just replace the " $.fn.almFilter" with "ajaxloadmore.filter". It worked on my end.
https://connekthq.com/plugins/ajax-load-more/docs/public-functions/#filter
