### ISSUE TITLE
$.fn.almFilter is not a function

### ISSUE THREAD

**Issue by apsolut** [dcooney/wordpress-ajax-load-more#157]
When updated to 5.0.1 I get some errors about: $.fn.almFilter
Checked:
- loaded after ajax-load-more
- no other conflicts (browser devtools console...)

When I install older version: 4.2.0.1 filter buttons are working again

**Comment by dcooney** [comment]
in 5.0 the callbacks  and public functions have changed since jQuery has been removed.
https://connekthq.com/plugins/ajax-load-more/docs/public-functions/#filter

You either need to update the functions in your script or enable Legacy Callbacks.
See the callback functions section here - https://connekthq.com/ajax-load-more-5-0/

**Comment by apsolut** [comment]
@dcooney  thanks,  removed $.fn , now the issue looks like no detection of ajaxStop, ajaxCompleted is working - that have sens... 
not sure how to detect multiple almComplete or almDone now...
https://connekthq.com/plugins/ajax-load-more/docs/callback-functions/almcomplete/

**Comment by dcooney** [comment]
You can only use 1 callback at a time. This has not changed. 
I don't know what `ajaxStop` or `ajaxCompleted` is. They are not part of ALM.

**Comment by apsolut** [comment]
ajaxStop was part of detection when all is loaded (all ajax requests) so we can execute something... ajaxCompleted when ajax on $(documents) has be done...  right now not sure how to detect that kind of things, as it looks like overwriting each other when we have multiple filters / queries listed :S

**Comment by dcooney** [comment]
Maybe those were part of jQuery?

**Comment by apsolut** [comment]
will try to use almDone and almComplete, https://connekthq.com/plugins/ajax-load-more/docs/callback-functions/
